import PDFDocument from "pdfkit";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const pdfDownload = async (req, res) => {
  const { result } = req.body;

  if (!result) {
    return res.status(400).json({ error: "No content provided!" });
  }

  const doc = new PDFDocument({ margin: 50 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", 'attachment; filename="PrepMateAI.pdf"');

  // Helper for section divider
  const sectionDivider = () => {
    doc.moveDown(0.5);
    doc
      .strokeColor("#dddddd")
      .lineWidth(1)
      .moveTo(50, doc.y)
      .lineTo(550, doc.y)
      .stroke();
    doc.moveDown();
  };

  const pageWidth = doc.page.width;

  // sizes
  const iconWidth = 40;
  const textWidth = 180;
  const gap = 10;

  // total width of both images
  const totalWidth = iconWidth + gap + textWidth;

  // start X position (center calculation)
  const startX = (pageWidth - totalWidth) / 2;

  doc.pipe(res);

  doc.rect(0, 30, doc.page.width, 70).fill("#4B4A48");

  // draw icon logo
  const logoPath = path.join(__dirname, "../assets/logoPrepMate.png");

  doc.image(logoPath, startX, 40, {
    width: iconWidth,
  });

  // draw text logo
  const textLogoPath = path.join(__dirname, "../assets/textPrepMate.png");

  doc.image(textLogoPath, startX + iconWidth + gap, 45, {
    width: textWidth,
  });

  doc.moveDown(6);

  doc.font("Helvetica").fontSize(14).fillColor("#333").text("Important Topics");

  sectionDivider();

  // Sub Topics
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#111").text("Sub Topics");

  doc.moveDown(0.5);

  Object.entries(result.subTopics).forEach(([, topics]) => {
    doc.moveDown(0.5);

    topics.forEach((t) => {
      doc.font("Helvetica").fontSize(12).text(`• ${t}`);
    });

    doc.moveDown(0.5);
  });

  sectionDivider();

  // Notes
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#111").text("Notes");

  doc.moveDown(0.5);

  doc
    .font("Helvetica")
    .fontSize(12)
    .fillColor("#333")
    .text(result.notes.replace(/[#*]/g, ""));

  sectionDivider();

  // Revision Points
  doc
    .font("Helvetica-Bold")
    .fontSize(16)
    .fillColor("#111")
    .text("Revision Points");

  doc.moveDown(0.5);

  result.revisionPoints.forEach((p) => {
    doc.font("Helvetica").fontSize(12).text(`• ${p}`);
  });

  sectionDivider();

  // Questions
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#111").text("Questions");

  doc.moveDown(0.5);

  // Short Questions
  doc.font("Helvetica-Bold").fontSize(13).text("Short Questions:");

  result.questions.short.forEach((q) => {
    doc.font("Helvetica").fontSize(12).text(`• ${q}`);
  });

  doc.moveDown(0.5);

  // Long Questions
  doc.font("Helvetica-Bold").fontSize(13).text("Long Questions:");

  result.questions.long.forEach((q) => {
    doc.font("Helvetica").fontSize(12).text(`• ${q}`);
  });

  doc.moveDown(0.5);

  // Diagram Question
  doc.font("Helvetica-Bold").fontSize(13).text("Diagram Question:");

  doc.font("Helvetica").fontSize(12).text(result.questions.diagram);

  // Footer
  doc.moveDown(2);

  doc.fontSize(10).fillColor("#888").text("Generated by PrepMate AI", {
    align: "center",
  });

  doc.end();
};
